image: trion/ng-cli-e2e:8.1.2

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm rebuild node-sass
    - npm run-script lint
    - npm run-script test
    - npm run-script e2e

build:
  stage: build
  script:
    - npm run-script build
    - npm run-script build example --prod
  cache:
    policy: pull
    paths:
      - node_modules/
